import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import LoginBtn from './loginBtn';
import { getServerSession } from 'next-auth' ;
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogoutBtn from './logoutBtn';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'VIVID',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session= await getServerSession(authOptions);
 
  return (
    <html lang="en">
      
      <body className={inter.className}>
        { 
            session? <div className='userInfo'>
            <img src={`${session.user.image}`} alt="userimg" />
            <span>{session.user.name} </span>
            {session ? <LogoutBtn></LogoutBtn> : null}
          </div> : null
        } 
        <div className="top-logo">
          <Link href="/"><img src="/img/logo2.png" alt="logo" /></Link>
        </div>
        <div className="g-menu">
          <ul>
            <li><Link href="/">HOME</Link></li>
            {session ? null : <li><LoginBtn></LoginBtn></li>}
            <li><Link href="/register">JOIN</Link></li>
            <li><Link href="/order">ORDER</Link></li>
            <li><Link href="/cart">CART</Link></li>
            <li><Link href="/notice">NOTICE</Link></li>
          </ul>
        </div>
        <nav className="menu">
          <ul>
            <li><Link href="/best100">BEST</Link></li>
            <li><Link href="/new">NEW</Link></li>
            <li><Link href="/dress">DRESS</Link></li>
            <li><Link href="/top">TOP</Link></li>
            <li><Link href="/bottom">BOTTOM</Link></li>
            <li><Link href="/outer">OUTER</Link></li>
            <li><Link href="/acc">ACC</Link></li>
            <li><Link href="/sale">SALE</Link></li>
          </ul>
        </nav>
        {children}
        <footer className="footer">
          <div className="footer-inner">
            <ul>
              <li>
                <h4>NOTIFICATION</h4>
                <ul>
                  <li><Link href="/">회사소개</Link></li>
                  <li><Link href="/">이용약관</Link></li>
                  <li><Link href="/">이용안내</Link></li>
                  <li><Link href="/">개인정보 취급방침</Link></li>
                  <li><Link href="/">협찬/제휴문의</Link></li>
                </ul>
              </li>
              <li>
                <h4>COMPANY INFOMATION</h4>
                <ul>
                  <li><Link href="/">compan. (주)띤컴</Link></li>
                  <li><Link href="/">Address. 서울 서초구 일성빌딩 8층</Link></li>
                  <li><Link href="/">Owner. lee sinchul</Link></li>
                  <li><Link href="/">Business License. 204-12-111211</Link></li>
                  <li><Link href="/">Copy Right &copy1 cho line. All Rights Reserved.</Link></li>
                  
                </ul>
              </li>
              <li>
                <h4>BANK ACCOUNT</h4>
                <ul>
                  <li><Link href="/">국민 2222-222-2222222</Link></li>
                  <li><Link href="/">농협 2221-222-2222223</Link></li>
                  <li><Link href="/">신한 2223-222-2222224</Link></li>
                  <li><Link href="/">우리 2224-222-2222225</Link></li>
                  <li><Link href="/">기업 2225-222-2222226</Link></li>
                  <li><Link href="/">카뱅 2226-222-2222227</Link></li>
                  
                </ul>
              </li>
              <li>
                <h4>CS CENTER</h4>
                <ul>
                  <li><Link href="/">weekday AM 10:00 - PM 4:00</Link></li>
                  <li><Link href="/">Lunch PM 12:00 - PM 1:00</Link></li>
                  <li><Link href="/">SAT/SUN/HOLIDAY.OFF</Link></li>
                  <li><span>전화량이 많아 게시판을 이용해주시면 <br />빠르게 답변을 받으실 수 있습니다.</span></li>
                </ul>
                  <p>5858-8282</p>
              </li>
            </ul>
          </div>
        </footer>
      </body>
    </html>
  )
}
